### ISSUE TITLE
Straddleboard enchantments are present when they shouldn't; or, the means of obtaining a straddleboard is missing when it shouldn't

### ISSUE THREAD

**Issue by beegyfleeg** [Vazkii/crucial2#105]
My friend obtained a enchanted book with "Lavawaxed" from a desert temple. This is an enchantment from Alex's Mobs, for an item called a straddleboard, associated with the mob "Straddler"

There are two potential issues here:

- The enchantments associated with the Straddleboard are present on some naturally-generated enchanted books.
- The Straddler and Stradpole (and as aside, Warped Mosco) do not spawn naturally, and do not appear in the mob dictionary. The crafting recipe for the Straddleboard does not appear in JEI.

**Comment by J053Fabi0** [comment]
I also want to know, what is this straddler? How to craft it or obtain it?
