### ISSUE TITLE
Line of sight on baby animals' hitboxes are too high

### ISSUE THREAD

**Issue by BlueVsRed12** [Vazkii/crucial2#109]
![image](https://user-images.githubusercontent.com/35225767/111718005-33daa000-8827-11eb-9b7a-c4cbbc7d7d4c.png)
This also causes tall animals' baby variants (such as baby cows / sheep, not pigs / chickens) to suffocate when directly underneath a solid block.
![image](https://user-images.githubusercontent.com/35225767/111718486-fc202800-8827-11eb-81e6-7d67ff73982c.png)
(pain)

I tried removing all the mods in the modpack but the issue remained.

**Comment by Vazkii** [comment]
yeah that
