### ISSUE TITLE
Ancient Tomes no longer appear in Stronghold Library chests (1.2.0)

### ISSUE THREAD

**Issue by Omnicsat** [Vazkii/crucial2#127]
I assume something to do with Yung's Strongholds being different structures than the vanilla ones, but Ancient Tomes appear to no longer show up as loot in Libraries at all, whereas they used to be very common (oftentimes around two per chest).

**Comment by Teacyn** [comment]
To add onto this, I believe that the Healer's Pouch may be unobtainable now? It's supposed to spawn in Mineshafts and Strongholds, and it already wasn't spawning in mineshafts.
