### ISSUE TITLE
Lakes generate in Abundance biomes

### ISSUE THREAD

**Issue by MobiusFlip** [Vazkii/crucial2#37]
![2021-02-09_14 20 53](https://user-images.githubusercontent.com/25667711/107416148-26bce980-6ae2-11eb-9fdf-14bb3376cfcb.png)

![2021-02-09_14 23 20](https://user-images.githubusercontent.com/25667711/107416407-71d6fc80-6ae2-11eb-9ff5-2729b7e638e4.png)

![2021-02-09_14 24 30](https://user-images.githubusercontent.com/25667711/107416482-89ae8080-6ae2-11eb-993b-bf9bfef22871.png)

Seems to be an issue in all three Abundance biomes: nemophila fields, lavender fields, and lavender forests.

**Comment by Tralomine** [comment]
I saw a lake in an autumn forest too

**Comment by Vazkii** [comment]
It's because the data pack can't changed modded biomes. Just be like that.
