### ISSUE TITLE
single glass pane invisible in windowlogged fences

### ISSUE THREAD

**Issue by kaeebonrai** [Vazkii/crucial2#71]
![windowlogging-fence](https://user-images.githubusercontent.com/723371/108613794-2c50f280-7445-11eb-9b6c-7444eaa735c7.png)

**Comment by teddy7777777** [comment]
I think that is more to do with how glass panes work rather then it being a straight up bug. Of course once you connect the pane to another pane it becomes viable again. Just to note, glass panes weren't meant to do this sort of thing, so It isn't going to be perfect

**Comment by Vazkii** [comment]
Yeah, I think that's just because the windowlogged fences don't count as normal fences. I'd report this to Windowlogging.
