### ISSUE TITLE
Small typo in JEI Info Tab for Quark Pipes

### ISSUE THREAD

**Issue by mfawc** [Vazkii/crucial2#91]
Quark Pipes:

> Put items in with a hopper. Items prefer to flow down, then fowards, sideways, and lastly upwards. Disable specific pipes with a redstone signal. Items can also fall out of and into open ends.

should be

> Put items in with a hopper. Items prefer to flow down, then **forwards**, sideways, and lastly upwards. Disable specific pipes with a redstone signal. Items can also fall out of and into open ends.

**Comment by teddy7777777** [comment]
I think it should be like this:
>Put items in with a hopper. Items prefer to flow **downwards**, then **forwards**, sideways, and lastly upwards. Disable specific pipes with a redstone signal. Items can also fall out of and into open ends.
but yes, definitely a typo
