### ISSUE TITLE
JEI Cattail Entry

### ISSUE THREAD

**Issue by FynnWaelsing** [Vazkii/crucial2#94]
It would be nice if the cattail seeds entry were more specific about how cattails have to be planted. Something like "Can also plant them **_on tilled dirt underwater_** to make more" would help. Thanks!

**Comment by teddy7777777** [comment]
Replacing the JEI description with this might be the best solution:

> Are collected by right clicking grown Cattalis. To plant these seeds you must till/hoe dirt which is underwater which will grow them into more Cattails
