### ISSUE TITLE
Missing wisteria post crafting recipes

### ISSUE THREAD

**Issue by MalcolmMacDonald** [Vazkii/crucial2#96]
Wisteria (and all other woods from Environmental) posts don't have crafting recipes.

**Comment by teddy7777777** [comment]
Can Reproduce and Confirm this is a bug

Only Post Crafting Recipes are missing for all 3 wood types added by Environmental (Willow, Cherry and Wisteria) along with their stripped variants

Have you tried to see if they are missing their crafting recipes with just Environmental standalone?
