### ISSUE TITLE
Using Glowing Ink Sac on wood sign caused client to crash from rendering NullRef

### ISSUE THREAD

**Issue by MalcolmMacDonald** [Vazkii/crucial2#99]
Crash report attached. Used Glowing Inc Sac on Spruce Sign that had text on it. 

[crash-2021-03-14_12.13.06-client.txt](https://github.com/Vazkii/crucial2/files/6137405/crash-2021-03-14_12.13.06-client.txt)

**Comment by teddy7777777** [comment]
Unable to reproduce. Possibly a bug caused by your OptiFine use. See if removing OptiFine fixes the issue

**Comment by MalcolmMacDonald** [comment]
This was fixed, but the resulting recipes give 1 post rather than the standard 8.
